export const styles = {
  imageCardRightContentOuter: {
    borderCollapse: 'collapse',
    msoTableLspace: '0pt',
    msoTableRspace: '0pt',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  imageCardRightContentInner: {
    padding: 0,
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  imageCardRightContentContainer: {
    borderCollapse: 'collapse',
    msoTableLspace: '0pt',
    msoTableRspace: '0pt',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  imageCardRightContent: {
    paddingTop: '18px',
    paddingRight: 0,
    paddingBottom: '18px',
    paddingLeft: '18px',
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  title: {
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  image: {
    maxWidth: '150px',
    borderRadius: '0%',
    border: 0,
    height: 'auto',
    outline: 'none',
    textDecoration: 'none',
    msInterpolationMode: 'bicubic',
    verticalAlign: 'bottom',
  },
  textContent: {
    paddingRight: '18px',
    paddingTop: '18px',
    paddingBottom: '18px',
    color: '#f2f2f2',
    fontFamily: 'Helvetica',
    fontSize: '14px',
    fontWeight: 'normal',
    textAlign: 'center',
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
    wordBreak: 'break-word',
    lineHeight: '150%',
  },
  docTitle: {
    textAlign: 'center',
    display: 'block',
    margin: 0,
    padding: 0,
    color: '#111111',
    fontFamily: '"Merriweather Sans", "Helvetica Neue",Helvetica, Arial, sans-serif',
    fontSize: '26px',
    fontStyle: 'normal',
    fontWeight: 'bold',
    lineHeight: '125%',
    letterSpacing: 'normal',
  },
  link: {
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
    color: '#111111',
    fontWeight: 'bold',
    textDecoration: 'underline',
  },
};
