export const styles = {
  imageBlock: {
    minWidth: '100%',
    borderCollapse: 'collapse',
    msoTableLspace: '0pt',
    msoTableRspace: '0pt',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  imageBlockInner: {
    padding: '9px',
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  imageContentContainer: {
    minWidth: '100%',
    borderCollapse: 'collapse',
    msoTableLspace: '0pt',
    msoTableRspace: '0pt',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  imageContent: {
    paddingRight: '9px',
    paddingLeft: '9px',
    paddingTop: 0,
    paddingBottom: 0,
    textAlign: 'center',
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  title: {
    msoLineHeightRule: 'exactly',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
  },
  img: {
    maxWidth: '15426px',
    paddingBottom: 0,
    display: 'inline !important',
    verticalAlign: 'bottom',
    border: 0,
    height: 'auto',
    outline: 'none',
    textDecoration: 'none',
    msInterpolationMode: 'bicubic',
  },
};
